### ISSUE TITLE
Lab 1

### ISSUE THREAD

**Issue by mohanty-sd** [vbncml/PHYS5394-gaukhar#1]
- **maxFreq** should not have the factor 2*pi in it. Instantaneous phase is defined without the 2*pi factor.
- "B is the coefficient and F is the vector of 2 frequencies [fo, f1] of the singnal": Correct typos and explain better what B and F are. For example, show the function formula in the help comments.

**Comment by gaukhar-n** [comment]
I addressed issues in lab_l3. Thanks!
